spring:
    application:
            name: Starter Project
    profiles:
        active: dev
    liquibase:
        change-log: classpath:db/changelog/db.changelog-master.xml
    jpa:
        properties:
            hibernate:
                generate_statistics: false

logging:
  level:
    org.springframework.security.authentication.dao.DaoAuthenticationProvider: warn
    org.springframework.security.authentication.ProviderManager: warn
    org.springframework.web.servlet.mvc.method.annotation.ExceptionHandlerExceptionResolver: info
    org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: off
    org.springframework.boot.autoconfigure.logging.ConditionEvaluationReportLogger: off
    org.hibernate.stat: off
    org.hibernate: warn

otp:
  audit-purge:
    enabled: true
    retention-days: 90
